[package]
name = "minijinja-go"
version = "0.0.0"
edition = "2021"

[dependencies]
minijinja-cabi = { git = "https://github.com/mitsuhiko/minijinja.git", tag = "2.15.1" }

[profile.release]
lto = true
codegen-units = 1
